import type { DashboardOverview } from "@/types/dashboard";

export const dashboardOverviewMock: DashboardOverview = {
  company: {
    name: "MTCprop",
    vertical: "Mesa proprietaria, educacao e aceleracao de traders",
    website: "https://mtcprop.com.br/",
    environment: "Operacao local",
    deploymentTarget: "Render em homologacao",
  },
  kpis: [
    {
      label: "Alunos ativos",
      value: "188",
      trend: "+14 no mes",
      hint: "Base atual com alunos em onboarding, treinamento e mesa real.",
      tone: "brand",
    },
    {
      label: "Inscricoes ativas",
      value: "134",
      trend: "71% da base",
      hint: "Planos em andamento com acompanhamento operacional do time.",
      tone: "neutral",
    },
    {
      label: "Acessos liberados",
      value: "121",
      trend: "9 pendencias",
      hint: "Permissoes ja entregues para salas, modulos e treinamentos.",
      tone: "brand",
    },
    {
      label: "Receita mensal",
      value: "R$ 61,8 mil",
      trend: "+8,4%",
      hint: "Projecao baseada nas inscricoes dos planos e recorrencias atuais.",
      tone: "warning",
    },
  ],
  guruMetrics: [
    {
      label: "Traders sincronizados",
      value: "1.004",
      trend: "Base de contatos da Guru",
      hint: "Contatos sincronizados via API de Contacts.",
      tone: "brand",
    },
    {
      label: "Vendas aprovadas",
      value: "318",
      trend: "Transacoes confirmadas",
      hint: "Vendas concluídas mapeadas a partir dos status da Guru.",
      tone: "neutral",
    },
    {
      label: "Transações totais",
      value: "1.738",
      trend: "Historico agregado",
      hint: "Contagem geral de transactions retornadas pela Guru.",
      tone: "warning",
    },
  ],
  students: [
    {
      id: "std-001",
      name: "Bruno Mendes",
      email: "bruno.mendes@exemplo.com",
      plan: "Intermediario",
      stage: "Treinamento",
      accessStatus: "Liberado",
      mentor: "Ana Ribeiro",
      updatedAt: "Atualizado ha 18 min",
    },
    {
      id: "std-002",
      name: "Leticia Castro",
      email: "leticia.castro@exemplo.com",
      plan: "Avancado",
      stage: "Simulador",
      accessStatus: "Em analise",
      mentor: "Pedro Valenca",
      updatedAt: "Atualizado ha 36 min",
    },
    {
      id: "std-003",
      name: "Tiago Faria",
      email: "tiago.faria@exemplo.com",
      plan: "Start",
      stage: "Onboarding",
      accessStatus: "Restrito",
      mentor: "Caio Moura",
      updatedAt: "Atualizado ha 1 h",
    },
    {
      id: "std-004",
      name: "Carla Muniz",
      email: "carla.muniz@exemplo.com",
      plan: "Expert",
      stage: "Mesa real",
      accessStatus: "Liberado",
      mentor: "Ana Ribeiro",
      updatedAt: "Atualizado ha 2 h",
    },
    {
      id: "std-005",
      name: "Leonardo Prado",
      email: "leonardo.prado@exemplo.com",
      plan: "Intermediario Fast",
      stage: "Avaliacao",
      accessStatus: "Em analise",
      mentor: "Felipe Costa",
      updatedAt: "Atualizado ha 3 h",
    },
  ],
  enrollments: [
    {
      label: "Novos leads",
      total: 23,
      description: "Interessados em contato com comercial e suporte.",
    },
    {
      label: "Onboarding",
      total: 14,
      description: "Alunos aguardando ativacao inicial e checklist.",
    },
    {
      label: "Ativos",
      total: 134,
      description: "Inscricoes com acompanhamento do time operacional.",
    },
    {
      label: "Revisao manual",
      total: 8,
      description: "Casos com pendencia de pagamento, acesso ou migracao.",
    },
  ],
  plans: [
    {
      name: "Start",
      activeStudents: 46,
      revenueShare: "R$ 13,6 mil",
      maxContracts: "5 contratos",
      highlight: "Entrada forte para novos operadores.",
    },
    {
      name: "Intermediario",
      activeStudents: 58,
      revenueShare: "R$ 18,9 mil",
      maxContracts: "10 contratos",
      highlight: "Maior concentracao da operacao hoje.",
    },
    {
      name: "Avancado",
      activeStudents: 22,
      revenueShare: "R$ 14,3 mil",
      maxContracts: "25 contratos",
      highlight: "Faixa com maior taxa de continuidade.",
    },
    {
      name: "Expert",
      activeStudents: 8,
      revenueShare: "R$ 9,8 mil",
      maxContracts: "50 contratos",
      highlight: "Perfil premium com alto acompanhamento.",
    },
  ],
  accessModules: [
    {
      name: "Sala ao vivo",
      active: 98,
      pending: 11,
      blocked: 5,
      description: "Acesso para acompanhamento das operacoes e calls.",
    },
    {
      name: "Biblioteca de aulas",
      active: 121,
      pending: 7,
      blocked: 3,
      description: "Treinamentos gravados, trilhas e materiais de apoio.",
    },
    {
      name: "Comunidade premium",
      active: 83,
      pending: 16,
      blocked: 9,
      description: "Grupo fechado para alunos ativos e operadores elegiveis.",
    },
    {
      name: "Suporte operacional",
      active: 114,
      pending: 4,
      blocked: 2,
      description: "Canal de atendimento para ativacao, reset e migracoes.",
    },
  ],
  pendingActions: [
    {
      title: "Validar novos pagamentos do plano Avancado",
      owner: "Financeiro",
      dueDate: "Hoje, 18:30",
      priority: "Alta",
      context: "7 alunos aguardando confirmacao para liberar o acesso completo.",
    },
    {
      title: "Revisar migracao para mesa real",
      owner: "Operacao",
      dueDate: "Seg, 09:00",
      priority: "Alta",
      context: "3 operadores bateram gatilho e precisam de troca de perfil.",
    },
    {
      title: "Atualizar trilha do Metodo Trader Consistente",
      owner: "Educacional",
      dueDate: "Seg, 14:00",
      priority: "Media",
      context: "Novo modulo sera liberado para turmas do Intermediario Fast.",
    },
    {
      title: "Auditar acessos bloqueados manualmente",
      owner: "Suporte",
      dueDate: "Ter, 11:00",
      priority: "Baixa",
      context: "Conferir casos antigos antes da virada da proxima quinzena.",
    },
  ],
  activityTimeline: [
    {
      title: "12 novos acessos foram liberados",
      type: "Permissoes",
      time: "Ha 14 min",
      note: "Liberacao em lote para os modulos de biblioteca e sala ao vivo.",
    },
    {
      title: "Financeiro confirmou 5 inscricoes do plano Intermediario",
      type: "Inscricoes",
      time: "Ha 39 min",
      note: "Fluxo concluido com onboarding automatico preparado para o suporte.",
    },
    {
      title: "Equipe operacional sinalizou 2 alunos para migracao",
      type: "Mesa real",
      time: "Ha 1 h",
      note: "Casos ja prontos para liberar os proximos acessos de ambiente.",
    },
    {
      title: "Nova revisao de conteudo publicada para a trilha de treinamento",
      type: "Educacao",
      time: "Ha 2 h",
      note: "Atualizacao focada em consistencia operacional e risco.",
    },
  ],
};
